# -*- coding: utf-8 -*-
"""forecast_admit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Q3HmPKYLXdX0W-rseAgtHMuQdHf9HSQ
"""

import joblib
import pandas as pd

model = joblib.load("saved_models/arima_model.pkl")

def forecast_admissions():
    forecast = model.forecast(steps=7)
    return {"admissions_forecast_next_7_days": list(map(int, forecast))}