# -*- coding: utf-8 -*-
"""predict_cost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wx_VHIZM3xLYC1bmPWSIfrUTW83Ptdvv
"""

import joblib
import numpy as np

model = joblib.load("saved_models/xgb_cost_model.pkl")

def predict_cost(data):
    features = np.array([[data.age, data.dm, data.htn, data.cad, data.ckd, data.season_num, data.stay]])
    prediction = model.predict(features)
    return {"predicted_cost": round(float(prediction[0]), 2)}