# -*- coding: utf-8 -*-
"""predict_stay

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e44wI0LC7fXoV5kcmdhFyO4v_cEA8blL
"""

import joblib
import numpy as np

model = joblib.load("saved_models/xgb_stay_model.pkl")

def predict_stay(data):
    features = np.array([[data.age, data.dm, data.htn, data.cad, data.ckd, data.season_num]])
    prediction = model.predict(features)
    return {"predicted_stay": round(float(prediction[0]), 2)}