# -*- coding: utf-8 -*-
"""optimizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zGN6WvGtJxVP_D1sAeR37Egu7XAmYVU
"""

from scipy.optimize import linprog

def optimize_resources():
    c = [1, 1]
    A = [[1, 0], [0, 1]]
    b = [100, 50]
    x_bounds = (0, 100)
    y_bounds = (0, 50)
    result = linprog(c, A_ub=A, b_ub=b, bounds=[x_bounds, y_bounds], method='highs')

    return {
        "optimized_beds": round(result.x[0]),
        "optimized_staff": round(result.x[1]),
        "status": result.message
    }