# -*- coding: utf-8 -*-
"""revised code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ECR2vVBK8hUOqNA5XhBQzBpQYDBIWwH
"""

# Imports and setup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor
from scipy.optimize import linprog
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
file_path = os.path.join(BASE_DIR, 'data', 'data.csv')
data = pd.read_csv(file_path)

data.columns = data.columns.str.strip().str.upper()
data['ADMISSION DATE'] = pd.to_datetime(data['ADMISSION DATE'], errors='coerce')
data.set_index('ADMISSION DATE', inplace=True)
data.dropna(how='all', inplace=True)

# Fill missing numeric values
numeric_cols = ['AGE', 'STAY', 'SMOKING', 'ALCOHOL', 'DM', 'HTN', 'CAD', 'CKD', 'RAISED CARDIAC ENZYMES']
data[numeric_cols] = data[numeric_cols].fillna(0)

# One-hot encoding
data = pd.get_dummies(data, columns=['ADMISSION TYPE', 'SEASON', 'DAY'], drop_first=True)

# Standardize numeric features
scaler = StandardScaler()
data[numeric_cols] = scaler.fit_transform(data[numeric_cols])

# Create season column from month
def assign_season(month):
    if month in [12, 1, 2]: return "Winter"
    elif month in [3, 4, 5]: return "Spring"
    elif month in [6, 7, 8]: return "Summer"
    else: return "Fall"

data['MONTH'] = data.index.month
data['SEASON'] = data['MONTH'].map(assign_season)
data['SEASON_NUM'] = data['SEASON'].map({"Winter": 1, "Spring": 2, "Summer": 3, "Fall": 4})

# --- Time Series Forecasting ---
ts_data = data.resample('D').size().to_frame(name='inflow').reset_index()
ts_data.rename(columns={'ADMISSION DATE': 'ds'}, inplace=True)
result = adfuller(ts_data['inflow'])
print('ADF Test (Original):', result[0], '| p-value:', result[1])
ts_data['inflow_diff'] = ts_data['inflow'].diff()
result = adfuller(ts_data['inflow_diff'].dropna())
print('ADF Test (Differenced):', result[0], '| p-value:', result[1])

model = ARIMA(ts_data['inflow'], order=(1, 1, 1))
model_fit = model.fit()
forecast = model_fit.forecast(steps=30)

# Plot forecast
plt.figure(figsize=(10, 4))
plt.plot(ts_data['inflow'], label='Original')
plt.plot(np.arange(len(ts_data), len(ts_data)+30), forecast, label='Forecast')
plt.legend()
plt.title("Admission Inflow Forecast")
plt.show()

# --- Length of Stay Model ---
X_stay = data[['AGE', 'DM', 'HTN', 'CAD', 'CKD', 'SEASON_NUM']]
y_stay = data['STAY']
X_train_stay, X_test_stay, y_train_stay, y_test_stay = train_test_split(X_stay, y_stay, test_size=0.2, random_state=42)
stay_model = XGBRegressor()
stay_model.fit(X_train_stay, y_train_stay)
stay_preds = stay_model.predict(X_test_stay)
print("\nStay Model Metrics:")
print("MSE:", mean_squared_error(y_test_stay, stay_preds))
print("MAE:", mean_absolute_error(y_test_stay, stay_preds))
print("R2 Score:", r2_score(y_test_stay, stay_preds))

# --- Resource Cost Estimation ---
feature_columns = ['AGE', 'ALCOHOL', 'SMOKING', 'DM', 'HTN', 'CAD', 'CKD', 'RAISED CARDIAC ENZYMES'] + \
                  list(data.filter(like='ADMISSION TYPE_').columns) + \
                  list(data.filter(like='SEASON_').columns) + \
                  list(data.filter(like='DAY_').columns)
X_cost = data[feature_columns]
y_cost = data['RESOURCE COST']
X_train_cost, X_test_cost, y_train_cost, y_test_cost = train_test_split(X_cost, y_cost, test_size=0.2, random_state=42)

xgb_model = XGBRegressor()
xgb_model.fit(X_train_cost, y_train_cost)
y_pred_cost = xgb_model.predict(X_test_cost)
print("\nResource Cost Estimation Metrics:")
print("MSE:", mean_squared_error(y_test_cost, y_pred_cost))
print("MAE:", mean_absolute_error(y_test_cost, y_pred_cost))
print("R2 Score:", r2_score(y_test_cost, y_pred_cost))

# --- Optimization ---
A = [[1, 0], [0, 1]]
b = [100, 50]
c = [1, 1]
x_bounds = (0, 100)
y_bounds = (0, 50)
result = linprog(c, A_ub=A, b_ub=b, bounds=[x_bounds, y_bounds], method='highs')
print("\nOptimal Resource Allocation (Beds, Staff):", result.x)

# --- Visualize Feature Importances ---
plt.figure(figsize=(10, 5))
sns.barplot(x=xgb_model.feature_importances_, y=X_cost.columns)
plt.title("Feature Importance for Resource Cost Prediction")
plt.tight_layout()
plt.show()