# -*- coding: utf-8 -*-
"""save_models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCP2UDMROD6n99lMXZd_tU5L9CAPinHf
"""

import pandas as pd
import joblib
import os
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from statsmodels.tsa.arima.model import ARIMA

# Create models directory if not exists
os.makedirs("backend/models", exist_ok=True)
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
file_path = os.path.join(BASE_DIR, 'data', 'set.csv')

# Add derived season_num column based on month
def assign_season(month):
    if month in [12, 1, 2]: return 1  # Winter
    elif month in [3, 4, 5]: return 2  # Spring
    elif month in [6, 7, 8]: return 3  # Summer
    else: return 4  # Fall

data['season_num'] = data['Admission Date'].dt.month.map(assign_season)

# Fill any missing values (ensure clean training)
data.fillna(0, inplace=True)

# --- 1. Stay Prediction Model ---
X_stay = data[['AGE', 'DM', 'HTN', 'CAD', 'CKD']]
y_stay = data['stay']
stay_model = DecisionTreeRegressor()
stay_model.fit(X_stay, y_stay)
joblib.dump(stay_model, "backend/models/stay_model.pkl")

# --- 2. Cost Prediction Model (includes season_num and stay) ---
X_cost = data[['season_num', 'stay', 'AGE', 'DM', 'HTN', 'CAD', 'CKD']]
y_cost = data['RESOURCE COST']
cost_model = XGBRegressor()
cost_model.fit(X_cost, y_cost)
joblib.dump(cost_model, "backend/models/xgb_model.pkl")

# --- 3. Admissions Forecasting Model (ARIMA) ---
ts_data = data.set_index('Admission Date').resample('D').size()
arima_model = ARIMA(ts_data, order=(1, 1, 1))
arima_fit = arima_model.fit()
arima_fit.save("backend/models/arima_model.pkl")

print("✅ All models trained and saved.")